### ISSUE TITLE
gulp build error (old npm version)

### ISSUE THREAD

**Issue by pivotal-plech** [pivotal-cf/pivotal-ui#372]
I'm trying to build a distribution locally and on `./update_styleguide.sh` things seem to blow up on `gulp build`.

```
➜  pivotal-ui git:(development) ./update_styleguide.sh

+ pushd library
~/Workspace/pivotal-ui/library ~/Workspace/pivotal-ui
+ gulp build
module.js:327
    throw err;
    ^

Error: Cannot find module 'debug'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/spencerhurst/Workspace/pivotal-ui/library/node_modules/strong-wait-till-listening/index.js:2:13)
    at Module._compile (module.js:409:26)
    at Module._extensions..js (module.js:416:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/spencerhurst/Workspace/pivotal-ui/library/node_modules/babel-core/node_modules/babel-register/lib/node.js:134:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
```

Any thoughts? Thanks in advance.

**Comment by pivotal-plech** [comment]
`npm i --save-dev debug` seemed to do the trick.

**Comment by charleshansen** [comment]
There is a known bug in one of our dependencies with this, but I haven't seen this forever. I believe the bug only occurs if you are using npm 2 (we are on npm 3). Installing debug at the top of library like that does work, it is just confusing since we don't directly use it.

**Comment by pivotal-plech** [comment]
Cool. Didn't realize npm was at 3 given I'm on a new machine and just installed node – which I thought would install the latest npm. To upgrade from 2 to 3 I had to:

`sudo npm install npm -g`
